docs_dir: docs/
extra:
  version:
    provider: mike
markdown_extensions:
  - attr_list
  - admonition
  - codehilite
  - footnotes
  - md_in_html
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
plugins:
  - include-markdown
  - search:
      lang:
        - en
  - awesome-pages
repo_name: terraform-aws-eks
repo_url: https://github.com/terraform-aws-modules/terraform-aws-eks
site_name: Terraform AWS EKS
site_url: https://terraform-aws-modules/terraform-aws-eks/
theme:
  favicon: assets/logo.png
  features:
    - navigation.tabs.sticky
  font:
    text: ember
  highlightjs: true
  hljs_languages:
    - yaml
    - json
  icon:
    admonition:
      abstract: octicons/checklist-16
      bug: octicons/bug-16
      danger: octicons/zap-16
      example: octicons/beaker-16
      failure: octicons/x-circle-16
      info: octicons/info-16
      note: octicons/tag-16
      question: octicons/question-16
      quote: octicons/quote-16
      success: octicons/check-16
      tip: octicons/squirrel-16
      warning: octicons/alert-16
    repo: fontawesome/brands/github
  logo: assets/terraform-aws.png
  name: material
  palette:
    accent: indgo
    primary: deep purple
